Update Android Gradle plugin to 4.1 version.
JLLeitschuh/ktlint-gradle pull request #411
Opened 2020-11-11 21:53 UTC by Tapchicoma

Breaking change as I used new api and dropped support for build variants meta tasks. New api does not provide such information.

2020-11-18 19:39 UTC, JLLeitschuh commented on samples/kotlin-mpp-android/build.gradle.kts
> +        val androidMain by getting
Are these still needed at all?

2020-11-18 19:41 UTC, JLLeitschuh commented on plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/android/AndroidPluginsApplier.kt
> +@file:Suppress("UnstableApiUsage")
Can you apply this a bit more specifically?

2020-11-18 19:43 UTC, JLLeitschuh requested changes
A few small things.

2020-12-07 20:07 UTC, Tapchicoma commented
@JLLeitschuh sorry for not addressing your review for a long time. Just did it, please check fixes.

2020-12-07 21:15 UTC, JLLeitschuh approved these changes
LGTM Thanks!

2020-12-07 21:40 UTC, merged