Check if hooks folder exists before using it
JLLeitschuh/ktlint-gradle pull request #563
Opened 2022-01-05 23:48 UTC by rbleuse

Fixes https://github.com/JLLeitschuh/ktlint-gradle/issues/557

2022-01-07 14:42 UTC, JLLeitschuh commented on plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/GitHook.kt
> +            logger.info("hooks directory doesn't exist, creating one")
```suggestion
            logger.info("git hooks directory doesn't exist, creating one")
```

2022-01-07 14:42 UTC, JLLeitschuh requested changes
This change looks good in general. Please add release notes. 🙂

2022-01-08 02:46 UTC, rbleuse commented
> This change looks good in general. Please add release notes. 🙂

@JLLeitschuh thanks, done, please check 🙂

2022-01-08 04:07 UTC, JLLeitschuh approved these changes
LGTM. I'm going to let the CI jobs run before merging

2022-01-12 04:19 UTC, merged