Configure configurations as resolvable non-consumable
JLLeitschuh/ktlint-gradle pull request #571
Opened 2022-01-27 14:41 UTC by tbroyer

Keeping the default of being consumable exposes them to
variant-aware resolution when the project is depended
upon from another project.

Also configure the configurations as non-visible for
similar reasons: those are specific to this project's
build and there's no reason to consume them from
another project.

Fix #523

2022-01-27 21:45 UTC, JLLeitschuh requested changes
Excellent!! This is exactly the cohesive contribution I appreciate! Thank you for the awesome test that so simply demonstrates this issue. Can you just add the change I suggest and then I'm happy to approve/merge this

2022-01-27 21:45 UTC, JLLeitschuh commented on plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt
> +    @DisplayName("Should not leak KtLint as a variant into consuming projects")
```suggestion
    /**
     * See: https://github.com/JLLeitschuh/ktlint-gradle/issues/523#issuecomment-1022522032
     */
    @DisplayName("Should not leak KtLint as a variant into consuming projects")
```

2022-01-28 10:37 UTC, tbroyer commented
I also added a changelog entry. The branch should be opened to maintainers though, so feel free to directly make changes there.

2022-01-28 13:12 UTC, JLLeitschuh approved these changes
LGTM!

2022-02-07 19:07 UTC, merged