support ktlint 0.45-0.48
JLLeitschuh/ktlint-gradle pull request #620
Opened 2023-01-12 17:50 UTC by wakingrufus

2023-01-12 17:53 UTC, wakingrufus commented on plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/testdsl/testDsl.kt
> -        const val CLEAN_SOURCES_FILE = "src/main/kotlin/clean-source.kt"
this now fails lint as an "unfixable" error so we need to change these

2023-01-12 18:03 UTC, wakingrufus commented on plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/worker/KtLintWorkAction.kt
> -            } catch (e: ParseException) {
ParseException was changed to KtLintParseException, so this will catch either one

2023-01-12 22:37 UTC, cyb3rko commented
Thank you, would be awesome it this will get merged and will work.

2023-01-24 15:07 UTC, JLLeitschuh commented on plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/worker/KtLintInvocation.kt
> +fun getEditorConfigPropertyClass(): Class<*> {
```suggestion
private fun getEditorConfigPropertyClass(): Class<*> {
```

OR

```suggestion
internal fun getEditorConfigPropertyClass(): Class<*> {
```

2023-01-24 15:08 UTC, JLLeitschuh commented on plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/worker/KtLintInvocation.kt
> +fun userDataToEditorConfigOverride(userData: Map<String, String>): Any {
```suggestion
private fun userDataToEditorConfigOverride(userData: Map<String, String>): Any {
```

OR

```suggestion
internal fun userDataToEditorConfigOverride(userData: Map<String, String>): Any {
```

2023-01-24 15:12 UTC, JLLeitschuh commented on plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/worker/KtLintInvocation.kt
> +val ruleEngineClass: Class<*>? by lazy {
```suggestion
private val legacyParamsClass: Class<*>? by lazy {
    try {
        Class.forName("com.pinterest.ktlint.core.KtLint\$Params")
    } catch (e: Exception) {
        null
    }
}

/**
 * detect the params class for ktlint 0.46.x and 0.47.x
 */
private val experimentalParamsClass: Class<*>? by lazy {
    try {
        Class.forName("com.pinterest.ktlint.core.KtLint\$ExperimentalParams")
    } catch (e: Exception) {
        null
    }
}

/**
 * detect the RuleEngine class for ktlint >= 0.48.0
 */
private val ruleEngineClass: Class<*>? by lazy {
```
OR
```suggestion
internal val legacyParamsClass: Class<*>? by lazy {
    try {
        Class.forName("com.pinterest.ktlint.core.KtLint\$Params")
    } catch (e: Exception) {
        null
    }
}

/**
 * detect the params class for ktlint 0.46.x and 0.47.x
 */
internal val experimentalParamsClass: Class<*>? by lazy {
    try {
        Class.forName("com.pinterest.ktlint.core.KtLint\$ExperimentalParams")
    } catch (e: Exception) {
        null
    }
}

/**
 * detect the RuleEngine class for ktlint >= 0.48.0
 */
internal val ruleEngineClass: Class<*>? by lazy {
```

2023-01-24 15:12 UTC, JLLeitschuh requested changes
Mostly just some access modifier changes requested

2023-01-25 17:16 UTC, JLLeitschuh commented on plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/worker/KtLintInvocation.kt
> +        val editorConfigOverride = userDataToEditorConfigOverride(userData)
Store this in a local lazy variable. It doesn't need to be created for every file

2023-01-27 16:21 UTC, JLLeitschuh approved these changes
LGTM!

2023-01-27 16:46 UTC, merged